build:
	mvn -f pom.xml clean package

run:
	mvn -f pom.xml exec:java -Dexec.mainClass="Main" -Dexec.args="4 /Users/adrian/Documents/facultate/an3/apd/tema1/checker/input/tests/test_5/articles.txt /Users/adrian/Documents/facultate/an3/apd/tema1/checker/input/tests/test_5/inputs.txt"

clean:
	mvn -f pom.xml clean